"""empty message

Revision ID: b1fd1a1e9d33
Revises: 8d6338c0c6e6
Create Date: 2019-11-12 13:54:51.392439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fd1a1e9d33'
down_revision = '8d6338c0c6e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('image_link', sa.String(length=500), nullable=False))
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('image_link', sa.String(length=500), nullable=False))
    op.add_column('venues', sa.Column('seeking_artist', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'seeking_artist')
    op.drop_column('venues', 'image_link')
    op.drop_column('artists', 'seeking_venue')
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'image_link')
    # ### end Alembic commands ###
